// ============================================================
// Mock Data — Amostra Realista de Jornadas e Telemetria
// ============================================================

import { v4 as uuidv4 } from 'uuid';
import type { AuditItem } from '@/types/audit';

const today = new Date().toISOString().slice(0, 10);

export const SAMPLE_AUDIT_ITEMS: AuditItem[] = [
  {
    id: uuidv4(),
    workspaceId: 'default',
    data: today,
    motorista: 'CARLOS EDUARDO SILVA',
    motoristaNormalizado: 'CARLOS EDUARDO SILVA',
    matricula: '10482',
    cpf: '123.456.789-00',
    batidasConciliadas: [
      {
        batida: { time: new Date(`${today}T06:00:00`), type: 'entrada', rawString: '06:00' },
        eventoRastreio: {
          motorista: 'Carlos Eduardo Silva',
          motoristaNormalizado: 'CARLOS EDUARDO SILVA',
          partida: new Date(`${today}T06:08:00`),
          parada: new Date(`${today}T11:55:00`),
          placa: 'ABC-1234',
        },
        diferencaMin: 8,
        status: 'confirmado',
      },
      {
        batida: { time: new Date(`${today}T12:00:00`), type: 'saida', rawString: '12:00' },
        eventoRastreio: {
          motorista: 'Carlos Eduardo Silva',
          motoristaNormalizado: 'CARLOS EDUARDO SILVA',
          partida: new Date(`${today}T06:08:00`),
          parada: new Date(`${today}T11:55:00`),
          placa: 'ABC-1234',
        },
        diferencaMin: 5,
        status: 'confirmado',
      },
      {
        batida: { time: new Date(`${today}T13:00:00`), type: 'entrada', rawString: '13:00' },
        eventoRastreio: {
          motorista: 'Carlos Eduardo Silva',
          motoristaNormalizado: 'CARLOS EDUARDO SILVA',
          partida: new Date(`${today}T13:04:00`),
          parada: new Date(`${today}T17:40:00`),
          placa: 'ABC-1234',
        },
        diferencaMin: 4,
        status: 'confirmado',
      },
      {
        batida: { time: new Date(`${today}T17:45:00`), type: 'saida', rawString: '17:45' },
        eventoRastreio: {
          motorista: 'Carlos Eduardo Silva',
          motoristaNormalizado: 'CARLOS EDUARDO SILVA',
          partida: new Date(`${today}T13:04:00`),
          parada: new Date(`${today}T17:40:00`),
          placa: 'ABC-1234',
        },
        diferencaMin: 5,
        status: 'confirmado',
      },
    ],
    bestDayShift: 0,
    heEfetivaMin: 65,
    hePrevistaMin: 60,
    excedenteMin: 0,
    excedenteClassificacao: 'dentro_padrao',
    resolvido: true,
    setor: 'Operações',
    causaProvavel: 'Jornada Regular Homologada',
    causaSugerida: 'Jornada Regular Homologada',
    justificativa: 'Horário homologado com 5 min de tolerância legal.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    workspaceId: 'default',
    data: today,
    motorista: 'MARCOS ANTONIO DE SOUZA',
    motoristaNormalizado: 'MARCOS ANTONIO DE SOUZA',
    matricula: '10512',
    cpf: '234.567.890-11',
    batidasConciliadas: [
      {
        batida: { time: new Date(`${today}T07:15:00`), type: 'entrada', rawString: '07:15' },
        eventoRastreio: {
          motorista: 'Marcos Antonio Souza',
          motoristaNormalizado: 'MARCOS ANTONIO DE SOUZA',
          partida: new Date(`${today}T07:22:00`),
          parada: new Date(`${today}T12:30:00`),
          placa: 'XYZ-9876',
        },
        diferencaMin: 7,
        status: 'confirmado',
      },
      {
        batida: { time: new Date(`${today}T20:45:00`), type: 'saida', rawString: '20:45' },
        eventoRastreio: {
          motorista: 'Marcos Antonio Souza',
          motoristaNormalizado: 'MARCOS ANTONIO DE SOUZA',
          partida: new Date(`${today}T13:30:00`),
          parada: new Date(`${today}T20:38:00`),
          placa: 'XYZ-9876',
        },
        diferencaMin: 7,
        status: 'confirmado',
      },
    ],
    bestDayShift: 0,
    heEfetivaMin: 185,
    hePrevistaMin: 40,
    excedenteMin: 145,
    excedenteClassificacao: 'acima_padrao',
    resolvido: false,
    setor: 'Logística',
    causaProvavel: 'Viagem Longa / Rota Estendida por Demanda',
    causaSugerida: 'Viagem Longa / Rota Estendida por Demanda',
    justificativa: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    workspaceId: 'default',
    data: today,
    motorista: 'ROBERTO CARLOS PEREIRA',
    motoristaNormalizado: 'ROBERTO CARLOS PEREIRA',
    matricula: '10634',
    cpf: '345.678.901-22',
    batidasConciliadas: [
      {
        batida: { time: new Date(`${today}T05:30:00`), type: 'entrada', rawString: '05:30' },
        eventoRastreio: {
          motorista: 'Roberto Carlos Pereira',
          motoristaNormalizado: 'ROBERTO CARLOS PEREIRA',
          partida: new Date(`${today}T06:45:00`),
          parada: new Date(`${today}T14:30:00`),
          placa: 'MNO-5544',
        },
        diferencaMin: 75,
        status: 'divergencia_forte',
      },
      {
        batida: { time: new Date(`${today}T14:40:00`), type: 'saida', rawString: '14:40' },
        eventoRastreio: {
          motorista: 'Roberto Carlos Pereira',
          motoristaNormalizado: 'ROBERTO CARLOS PEREIRA',
          partida: new Date(`${today}T06:45:00`),
          parada: new Date(`${today}T14:30:00`),
          placa: 'MNO-5544',
        },
        diferencaMin: 10,
        status: 'confirmado',
      },
    ],
    bestDayShift: 0,
    heEfetivaMin: 80,
    hePrevistaMin: 0,
    excedenteMin: 80,
    excedenteClassificacao: 'acima_padrao',
    interjornadaMin: 540,
    interjornadaDeficit: 120, // 9h de descanso vs 11h exigidas
    resolvido: false,
    setor: 'Operações',
    causaProvavel: 'Déficit de Interjornada (< 11h regulamentares)',
    causaSugerida: 'Déficit de Interjornada (< 11h regulamentares)',
    justificativa: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    workspaceId: 'default',
    data: today,
    motorista: 'LUCAS FERNANDES LIMA',
    motoristaNormalizado: 'LUCAS FERNANDES LIMA',
    matricula: '10701',
    cpf: '456.789.012-33',
    batidasConciliadas: [
      {
        batida: { time: new Date(`${today}T08:00:00`), type: 'entrada', rawString: '08:00' },
        diferencaMin: 999,
        status: 'sem_cobertura',
      },
      {
        batida: { time: new Date(`${today}T17:20:00`), type: 'saida', rawString: '17:20' },
        diferencaMin: 999,
        status: 'sem_cobertura',
      },
    ],
    bestDayShift: 0,
    heEfetivaMin: 40,
    hePrevistaMin: 0,
    excedenteMin: 40,
    excedenteClassificacao: 'sem_referencia',
    resolvido: false,
    setor: 'Manutenção',
    causaProvavel: 'Veículo Sem Comunicação / Rastreador Inativo',
    causaSugerida: 'Veículo Sem Comunicação / Rastreador Inativo',
    justificativa: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    workspaceId: 'default',
    data: today,
    motorista: 'FERNANDO HENRIQUE ALVES',
    motoristaNormalizado: 'FERNANDO HENRIQUE ALVES',
    matricula: '10889',
    cpf: '567.890.123-44',
    batidasConciliadas: [
      {
        batida: { time: new Date(`${today}T14:00:00`), type: 'entrada', rawString: '14:00' },
        eventoRastreio: {
          motorista: 'Fernando Alves',
          motoristaNormalizado: 'FERNANDO HENRIQUE ALVES',
          partida: new Date(`${today}T14:05:00`),
          parada: new Date(`${today}T22:30:00`),
          placa: 'KJH-3321',
        },
        diferencaMin: 5,
        status: 'confirmado',
      },
      {
        batida: { time: new Date(`${today}T23:35:00`), type: 'saida', rawString: '23:35' },
        eventoRastreio: {
          motorista: 'Fernando Alves',
          motoristaNormalizado: 'FERNANDO HENRIQUE ALVES',
          partida: new Date(`${today}T14:05:00`),
          parada: new Date(`${today}T22:30:00`),
          placa: 'KJH-3321',
        },
        diferencaMin: 65,
        status: 'divergencia_forte',
      },
    ],
    bestDayShift: 0,
    heEfetivaMin: 95,
    hePrevistaMin: 30,
    excedenteMin: 65,
    excedenteClassificacao: 'acima_padrao',
    resolvido: false,
    setor: 'Operações',
    causaProvavel: 'Retardo de Saída no Ponto vs Desligamento do Veículo',
    causaSugerida: 'Retardo de Saída no Ponto vs Desligamento do Veículo',
    justificativa: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
